title: ' '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4fa3bd8b-5e0c-4e6d-8f8f-e83a80277995.png
description: Let Us Design Your Dreams
color:
  saturation: 0.6233413664158434
  brandStrength: 0.5640689567662776
  rhythmicContrast: 0.02455369406379759
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  lightness: 0.9530550763010979
typography_spectrum: 0.06827601068653166
layout_spectrum: 0.9713262
name: ' '
