typography_spectrum: 0.8141408755909652
color:
  brandStrength: 0.8385643099900335
  lightness: 0.4970482657663524
  saturation: 0.8582038911990821
  rhythmicContrast: 0.4840615934226662
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
layout_spectrum: 0.09511178499087691
name: Modern Designs
navigation:
  - name: Semi-Automatic Innovation
    id: d7e34751-7dcb-468d-a2a8-53614fd9a086
    type: content
  - name: Home
    url: moderndesigns.biz
    type: external
title: Modern Designs
description: Let Us Design Your Dreams
