typography_spectrum: 0.06827601068653166
color:
  saturation: 0.6233413664158434
  brandStrength: 0.5640689567662776
  lightness: 0.9530550763010979
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.024553694063797593
layout_spectrum: 0.2448850553482771
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4fa3bd8b-5e0c-4e6d-8f8f-e83a80277995.png
name: ' '
navigation:
  - name: Semi-Automatic Innovation
    id: d7e34751-7dcb-468d-a2a8-53614fd9a086
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ' '
description: Let Us Design Your Dreams
