title: Modern Designs
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4fa3bd8b-5e0c-4e6d-8f8f-e83a80277995.png
color:
  saturation: 0.9047640203498304
  brandStrength: 0.8782086183782667
  lightness: 0.028048427309840918
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.7338414834812284
typography_spectrum: 0.764173176838085
description: Let Us Design Your Dreams
navigation:
  - name: Home
    url: moderndesigns.biz
    type: external
  - name: Semi-Automatic Innovation
    id: d7e34751-7dcb-468d-a2a8-53614fd9a086
    type: content
layout_spectrum: 0.7154683151748031
name: Modern Designs
